// Code generated by MockGen. DO NOT EDIT.
// Source: infra/porto/porto/src/api/go/porto/porto.go
//
// Generated by this command:
//
//	mockgen -source=infra/porto/porto/src/api/go/porto/porto.go -destination=infra/porto/porto/src/api/go/porto/porto_mock.go -package=porto
//

// Package porto is a generated GoMock package.
package porto

import (
	reflect "reflect"
	syscall "syscall"
	time "time"

	proto "a.yandex-team.ru/library/cpp/porto/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockPortoAPI is a mock of PortoAPI interface.
type MockPortoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockPortoAPIMockRecorder
	isgomock struct{}
}

// MockPortoAPIMockRecorder is the mock recorder for MockPortoAPI.
type MockPortoAPIMockRecorder struct {
	mock *MockPortoAPI
}

// NewMockPortoAPI creates a new mock instance.
func NewMockPortoAPI(ctrl *gomock.Controller) *MockPortoAPI {
	mock := &MockPortoAPI{ctrl: ctrl}
	mock.recorder = &MockPortoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortoAPI) EXPECT() *MockPortoAPIMockRecorder {
	return m.recorder
}

// AttachProcess mocks base method.
func (m *MockPortoAPI) AttachProcess(name string, pid uint32, comm string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachProcess", name, pid, comm)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachProcess indicates an expected call of AttachProcess.
func (mr *MockPortoAPIMockRecorder) AttachProcess(name, pid, comm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachProcess", reflect.TypeOf((*MockPortoAPI)(nil).AttachProcess), name, pid, comm)
}

// Call mocks base method.
func (m *MockPortoAPI) Call(arg0 *proto.TContainerRequest) (*proto.TContainerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", arg0)
	ret0, _ := ret[0].(*proto.TContainerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Call indicates an expected call of Call.
func (mr *MockPortoAPIMockRecorder) Call(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockPortoAPI)(nil).Call), arg0)
}

// CallTimeout mocks base method.
func (m *MockPortoAPI) CallTimeout(arg0 *proto.TContainerRequest, arg1 time.Duration) (*proto.TContainerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallTimeout", arg0, arg1)
	ret0, _ := ret[0].(*proto.TContainerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallTimeout indicates an expected call of CallTimeout.
func (mr *MockPortoAPIMockRecorder) CallTimeout(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallTimeout", reflect.TypeOf((*MockPortoAPI)(nil).CallTimeout), arg0, arg1)
}

// Close mocks base method.
func (m *MockPortoAPI) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPortoAPIMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPortoAPI)(nil).Close))
}

// Connect mocks base method.
func (m *MockPortoAPI) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockPortoAPIMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockPortoAPI)(nil).Connect))
}

// ConvertPath mocks base method.
func (m *MockPortoAPI) ConvertPath(path, src, dest string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertPath", path, src, dest)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertPath indicates an expected call of ConvertPath.
func (mr *MockPortoAPIMockRecorder) ConvertPath(path, src, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertPath", reflect.TypeOf((*MockPortoAPI)(nil).ConvertPath), path, src, dest)
}

// Create mocks base method.
func (m *MockPortoAPI) Create(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPortoAPIMockRecorder) Create(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPortoAPI)(nil).Create), name)
}

// CreateFromSpec mocks base method.
func (m *MockPortoAPI) CreateFromSpec(spec *proto.TContainerSpec, volumes []*proto.TVolumeSpec, start bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFromSpec", spec, volumes, start)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFromSpec indicates an expected call of CreateFromSpec.
func (mr *MockPortoAPIMockRecorder) CreateFromSpec(spec, volumes, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFromSpec", reflect.TypeOf((*MockPortoAPI)(nil).CreateFromSpec), spec, volumes, start)
}

// CreateVolume mocks base method.
func (m *MockPortoAPI) CreateVolume(path string, config map[string]string) (*TVolumeDescription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVolume", path, config)
	ret0, _ := ret[0].(*TVolumeDescription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVolume indicates an expected call of CreateVolume.
func (mr *MockPortoAPIMockRecorder) CreateVolume(path, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVolume", reflect.TypeOf((*MockPortoAPI)(nil).CreateVolume), path, config)
}

// CreateWeak mocks base method.
func (m *MockPortoAPI) CreateWeak(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWeak", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWeak indicates an expected call of CreateWeak.
func (mr *MockPortoAPIMockRecorder) CreateWeak(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWeak", reflect.TypeOf((*MockPortoAPI)(nil).CreateWeak), name)
}

// Destroy mocks base method.
func (m *MockPortoAPI) Destroy(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destroy", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy.
func (mr *MockPortoAPIMockRecorder) Destroy(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockPortoAPI)(nil).Destroy), name)
}

// Dlist mocks base method.
func (m *MockPortoAPI) Dlist() ([]TData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dlist")
	ret0, _ := ret[0].([]TData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dlist indicates an expected call of Dlist.
func (mr *MockPortoAPIMockRecorder) Dlist() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dlist", reflect.TypeOf((*MockPortoAPI)(nil).Dlist))
}

// DockerImageStatus mocks base method.
func (m *MockPortoAPI) DockerImageStatus(name, place string) (*proto.TDockerImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DockerImageStatus", name, place)
	ret0, _ := ret[0].(*proto.TDockerImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DockerImageStatus indicates an expected call of DockerImageStatus.
func (mr *MockPortoAPIMockRecorder) DockerImageStatus(name, place any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DockerImageStatus", reflect.TypeOf((*MockPortoAPI)(nil).DockerImageStatus), name, place)
}

// ExportLayer mocks base method.
func (m *MockPortoAPI) ExportLayer(volume, tarball string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportLayer", volume, tarball)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportLayer indicates an expected call of ExportLayer.
func (mr *MockPortoAPIMockRecorder) ExportLayer(volume, tarball any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportLayer", reflect.TypeOf((*MockPortoAPI)(nil).ExportLayer), volume, tarball)
}

// Get mocks base method.
func (m *MockPortoAPI) Get(names, properties []string) (*proto.TContainerGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", names, properties)
	ret0, _ := ret[0].(*proto.TContainerGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPortoAPIMockRecorder) Get(names, properties any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPortoAPI)(nil).Get), names, properties)
}

// GetData mocks base method.
func (m *MockPortoAPI) GetData(name, data string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", name, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *MockPortoAPIMockRecorder) GetData(name, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockPortoAPI)(nil).GetData), name, data)
}

// GetLayerPrivate mocks base method.
func (m *MockPortoAPI) GetLayerPrivate(layer, place string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLayerPrivate", layer, place)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLayerPrivate indicates an expected call of GetLayerPrivate.
func (mr *MockPortoAPIMockRecorder) GetLayerPrivate(layer, place any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLayerPrivate", reflect.TypeOf((*MockPortoAPI)(nil).GetLayerPrivate), layer, place)
}

// GetProperties mocks base method.
func (m *MockPortoAPI) GetProperties(names, properties []string) (map[string]map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProperties", names, properties)
	ret0, _ := ret[0].(map[string]map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProperties indicates an expected call of GetProperties.
func (mr *MockPortoAPIMockRecorder) GetProperties(names, properties any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProperties", reflect.TypeOf((*MockPortoAPI)(nil).GetProperties), names, properties)
}

// GetProperty mocks base method.
func (m *MockPortoAPI) GetProperty(name, property string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProperty", name, property)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProperty indicates an expected call of GetProperty.
func (mr *MockPortoAPIMockRecorder) GetProperty(name, property any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProperty", reflect.TypeOf((*MockPortoAPI)(nil).GetProperty), name, property)
}

// GetTimeout mocks base method.
func (m *MockPortoAPI) GetTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetTimeout indicates an expected call of GetTimeout.
func (mr *MockPortoAPIMockRecorder) GetTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeout", reflect.TypeOf((*MockPortoAPI)(nil).GetTimeout))
}

// GetVersion mocks base method.
func (m *MockPortoAPI) GetVersion() (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockPortoAPIMockRecorder) GetVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockPortoAPI)(nil).GetVersion))
}

// GetVolume mocks base method.
func (m *MockPortoAPI) GetVolume(path string) (*TVolumeDescription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolume", path)
	ret0, _ := ret[0].(*TVolumeDescription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolume indicates an expected call of GetVolume.
func (mr *MockPortoAPIMockRecorder) GetVolume(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolume", reflect.TypeOf((*MockPortoAPI)(nil).GetVolume), path)
}

// ImportLayer mocks base method.
func (m *MockPortoAPI) ImportLayer(layer, tarball string, merge bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportLayer", layer, tarball, merge)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportLayer indicates an expected call of ImportLayer.
func (mr *MockPortoAPIMockRecorder) ImportLayer(layer, tarball, merge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportLayer", reflect.TypeOf((*MockPortoAPI)(nil).ImportLayer), layer, tarball, merge)
}

// ImportLayer4 mocks base method.
func (m *MockPortoAPI) ImportLayer4(layer, tarball string, merge bool, place, privateValue string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportLayer4", layer, tarball, merge, place, privateValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportLayer4 indicates an expected call of ImportLayer4.
func (mr *MockPortoAPIMockRecorder) ImportLayer4(layer, tarball, merge, place, privateValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportLayer4", reflect.TypeOf((*MockPortoAPI)(nil).ImportLayer4), layer, tarball, merge, place, privateValue)
}

// IsConnected mocks base method.
func (m *MockPortoAPI) IsConnected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConnected indicates an expected call of IsConnected.
func (mr *MockPortoAPIMockRecorder) IsConnected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnected", reflect.TypeOf((*MockPortoAPI)(nil).IsConnected))
}

// Kill mocks base method.
func (m *MockPortoAPI) Kill(name string, sig syscall.Signal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kill", name, sig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Kill indicates an expected call of Kill.
func (mr *MockPortoAPIMockRecorder) Kill(name, sig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kill", reflect.TypeOf((*MockPortoAPI)(nil).Kill), name, sig)
}

// LinkVolume mocks base method.
func (m *MockPortoAPI) LinkVolume(path, container string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkVolume", path, container)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkVolume indicates an expected call of LinkVolume.
func (mr *MockPortoAPIMockRecorder) LinkVolume(path, container any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkVolume", reflect.TypeOf((*MockPortoAPI)(nil).LinkVolume), path, container)
}

// LinkVolumeTarget mocks base method.
func (m *MockPortoAPI) LinkVolumeTarget(path, container, target string, required, readOnly bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkVolumeTarget", path, container, target, required, readOnly)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkVolumeTarget indicates an expected call of LinkVolumeTarget.
func (mr *MockPortoAPIMockRecorder) LinkVolumeTarget(path, container, target, required, readOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkVolumeTarget", reflect.TypeOf((*MockPortoAPI)(nil).LinkVolumeTarget), path, container, target, required, readOnly)
}

// List mocks base method.
func (m *MockPortoAPI) List() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPortoAPIMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPortoAPI)(nil).List))
}

// ListContainers mocks base method.
func (m *MockPortoAPI) ListContainers(mask string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContainers", mask)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContainers indicates an expected call of ListContainers.
func (mr *MockPortoAPIMockRecorder) ListContainers(mask any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContainers", reflect.TypeOf((*MockPortoAPI)(nil).ListContainers), mask)
}

// ListDockerImages mocks base method.
func (m *MockPortoAPI) ListDockerImages(place, mask string) ([]*proto.TDockerImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDockerImages", place, mask)
	ret0, _ := ret[0].([]*proto.TDockerImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDockerImages indicates an expected call of ListDockerImages.
func (mr *MockPortoAPIMockRecorder) ListDockerImages(place, mask any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDockerImages", reflect.TypeOf((*MockPortoAPI)(nil).ListDockerImages), place, mask)
}

// ListLayers mocks base method.
func (m *MockPortoAPI) ListLayers() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLayers")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLayers indicates an expected call of ListLayers.
func (mr *MockPortoAPIMockRecorder) ListLayers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLayers", reflect.TypeOf((*MockPortoAPI)(nil).ListLayers))
}

// ListLayers2 mocks base method.
func (m *MockPortoAPI) ListLayers2(place, mask string) ([]TLayerDescription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLayers2", place, mask)
	ret0, _ := ret[0].([]TLayerDescription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLayers2 indicates an expected call of ListLayers2.
func (mr *MockPortoAPIMockRecorder) ListLayers2(place, mask any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLayers2", reflect.TypeOf((*MockPortoAPI)(nil).ListLayers2), place, mask)
}

// ListStorage mocks base method.
func (m *MockPortoAPI) ListStorage(place, mask string) ([]TStorageDescription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStorage", place, mask)
	ret0, _ := ret[0].([]TStorageDescription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStorage indicates an expected call of ListStorage.
func (mr *MockPortoAPIMockRecorder) ListStorage(place, mask any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStorage", reflect.TypeOf((*MockPortoAPI)(nil).ListStorage), place, mask)
}

// ListVolumeProperties mocks base method.
func (m *MockPortoAPI) ListVolumeProperties() ([]TProperty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVolumeProperties")
	ret0, _ := ret[0].([]TProperty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVolumeProperties indicates an expected call of ListVolumeProperties.
func (mr *MockPortoAPIMockRecorder) ListVolumeProperties() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVolumeProperties", reflect.TypeOf((*MockPortoAPI)(nil).ListVolumeProperties))
}

// ListVolumes mocks base method.
func (m *MockPortoAPI) ListVolumes(path, container string) ([]*TVolumeDescription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVolumes", path, container)
	ret0, _ := ret[0].([]*TVolumeDescription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVolumes indicates an expected call of ListVolumes.
func (mr *MockPortoAPIMockRecorder) ListVolumes(path, container any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVolumes", reflect.TypeOf((*MockPortoAPI)(nil).ListVolumes), path, container)
}

// Pause mocks base method.
func (m *MockPortoAPI) Pause(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pause indicates an expected call of Pause.
func (mr *MockPortoAPIMockRecorder) Pause(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockPortoAPI)(nil).Pause), name)
}

// Plist mocks base method.
func (m *MockPortoAPI) Plist() ([]TProperty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Plist")
	ret0, _ := ret[0].([]TProperty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Plist indicates an expected call of Plist.
func (mr *MockPortoAPIMockRecorder) Plist() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Plist", reflect.TypeOf((*MockPortoAPI)(nil).Plist))
}

// PullDockerImage mocks base method.
func (m *MockPortoAPI) PullDockerImage(image DockerImage, creds DockerRegistryCredentials) (*proto.TDockerImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullDockerImage", image, creds)
	ret0, _ := ret[0].(*proto.TDockerImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullDockerImage indicates an expected call of PullDockerImage.
func (mr *MockPortoAPIMockRecorder) PullDockerImage(image, creds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullDockerImage", reflect.TypeOf((*MockPortoAPI)(nil).PullDockerImage), image, creds)
}

// ReadResponse mocks base method.
func (m *MockPortoAPI) ReadResponse() (*proto.TContainerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadResponse")
	ret0, _ := ret[0].(*proto.TContainerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadResponse indicates an expected call of ReadResponse.
func (mr *MockPortoAPIMockRecorder) ReadResponse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadResponse", reflect.TypeOf((*MockPortoAPI)(nil).ReadResponse))
}

// RemoveDockerImage mocks base method.
func (m *MockPortoAPI) RemoveDockerImage(name, place string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDockerImage", name, place)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDockerImage indicates an expected call of RemoveDockerImage.
func (mr *MockPortoAPIMockRecorder) RemoveDockerImage(name, place any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDockerImage", reflect.TypeOf((*MockPortoAPI)(nil).RemoveDockerImage), name, place)
}

// RemoveLayer mocks base method.
func (m *MockPortoAPI) RemoveLayer(layer string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLayer", layer)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLayer indicates an expected call of RemoveLayer.
func (mr *MockPortoAPIMockRecorder) RemoveLayer(layer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLayer", reflect.TypeOf((*MockPortoAPI)(nil).RemoveLayer), layer)
}

// RemoveLayer2 mocks base method.
func (m *MockPortoAPI) RemoveLayer2(layer, place string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLayer2", layer, place)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLayer2 indicates an expected call of RemoveLayer2.
func (mr *MockPortoAPIMockRecorder) RemoveLayer2(layer, place any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLayer2", reflect.TypeOf((*MockPortoAPI)(nil).RemoveLayer2), layer, place)
}

// RemoveStorage mocks base method.
func (m *MockPortoAPI) RemoveStorage(name, place string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveStorage", name, place)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveStorage indicates an expected call of RemoveStorage.
func (mr *MockPortoAPIMockRecorder) RemoveStorage(name, place any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveStorage", reflect.TypeOf((*MockPortoAPI)(nil).RemoveStorage), name, place)
}

// Resume mocks base method.
func (m *MockPortoAPI) Resume(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resume indicates an expected call of Resume.
func (mr *MockPortoAPIMockRecorder) Resume(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockPortoAPI)(nil).Resume), name)
}

// SetAutoReconnect mocks base method.
func (m *MockPortoAPI) SetAutoReconnect(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAutoReconnect", arg0)
}

// SetAutoReconnect indicates an expected call of SetAutoReconnect.
func (mr *MockPortoAPIMockRecorder) SetAutoReconnect(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAutoReconnect", reflect.TypeOf((*MockPortoAPI)(nil).SetAutoReconnect), arg0)
}

// SetLayerPrivate mocks base method.
func (m *MockPortoAPI) SetLayerPrivate(layer, place, privateValue string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLayerPrivate", layer, place, privateValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLayerPrivate indicates an expected call of SetLayerPrivate.
func (mr *MockPortoAPIMockRecorder) SetLayerPrivate(layer, place, privateValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLayerPrivate", reflect.TypeOf((*MockPortoAPI)(nil).SetLayerPrivate), layer, place, privateValue)
}

// SetProperty mocks base method.
func (m *MockPortoAPI) SetProperty(name, property, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProperty", name, property, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProperty indicates an expected call of SetProperty.
func (mr *MockPortoAPIMockRecorder) SetProperty(name, property, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProperty", reflect.TypeOf((*MockPortoAPI)(nil).SetProperty), name, property, value)
}

// SetTimeout mocks base method.
func (m *MockPortoAPI) SetTimeout(timeout time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTimeout", timeout)
}

// SetTimeout indicates an expected call of SetTimeout.
func (mr *MockPortoAPIMockRecorder) SetTimeout(timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTimeout", reflect.TypeOf((*MockPortoAPI)(nil).SetTimeout), timeout)
}

// Start mocks base method.
func (m *MockPortoAPI) Start(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockPortoAPIMockRecorder) Start(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockPortoAPI)(nil).Start), name)
}

// Stop mocks base method.
func (m *MockPortoAPI) Stop(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockPortoAPIMockRecorder) Stop(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockPortoAPI)(nil).Stop), name)
}

// StopTimeout mocks base method.
func (m *MockPortoAPI) StopTimeout(name string, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopTimeout", name, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopTimeout indicates an expected call of StopTimeout.
func (mr *MockPortoAPIMockRecorder) StopTimeout(name, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopTimeout", reflect.TypeOf((*MockPortoAPI)(nil).StopTimeout), name, timeout)
}

// TuneVolume mocks base method.
func (m *MockPortoAPI) TuneVolume(path string, config map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TuneVolume", path, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// TuneVolume indicates an expected call of TuneVolume.
func (mr *MockPortoAPIMockRecorder) TuneVolume(path, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TuneVolume", reflect.TypeOf((*MockPortoAPI)(nil).TuneVolume), path, config)
}

// UnlinkVolume mocks base method.
func (m *MockPortoAPI) UnlinkVolume(path, container string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkVolume", path, container)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkVolume indicates an expected call of UnlinkVolume.
func (mr *MockPortoAPIMockRecorder) UnlinkVolume(path, container any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkVolume", reflect.TypeOf((*MockPortoAPI)(nil).UnlinkVolume), path, container)
}

// UnlinkVolumeStrict mocks base method.
func (m *MockPortoAPI) UnlinkVolumeStrict(path, container, target string, strict bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkVolumeStrict", path, container, target, strict)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkVolumeStrict indicates an expected call of UnlinkVolumeStrict.
func (mr *MockPortoAPIMockRecorder) UnlinkVolumeStrict(path, container, target, strict any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkVolumeStrict", reflect.TypeOf((*MockPortoAPI)(nil).UnlinkVolumeStrict), path, container, target, strict)
}

// UnlinkVolumeTarget mocks base method.
func (m *MockPortoAPI) UnlinkVolumeTarget(path, container, target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkVolumeTarget", path, container, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkVolumeTarget indicates an expected call of UnlinkVolumeTarget.
func (mr *MockPortoAPIMockRecorder) UnlinkVolumeTarget(path, container, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkVolumeTarget", reflect.TypeOf((*MockPortoAPI)(nil).UnlinkVolumeTarget), path, container, target)
}

// UpdateFromSpec mocks base method.
func (m *MockPortoAPI) UpdateFromSpec(spec *proto.TContainerSpec, start bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFromSpec", spec, start)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFromSpec indicates an expected call of UpdateFromSpec.
func (mr *MockPortoAPIMockRecorder) UpdateFromSpec(spec, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFromSpec", reflect.TypeOf((*MockPortoAPI)(nil).UpdateFromSpec), spec, start)
}

// Wait mocks base method.
func (m *MockPortoAPI) Wait(containers []string, timeout time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", containers, timeout)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Wait indicates an expected call of Wait.
func (mr *MockPortoAPIMockRecorder) Wait(containers, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockPortoAPI)(nil).Wait), containers, timeout)
}

// WriteRequest mocks base method.
func (m *MockPortoAPI) WriteRequest(arg0 *proto.TContainerRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteRequest", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteRequest indicates an expected call of WriteRequest.
func (mr *MockPortoAPIMockRecorder) WriteRequest(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteRequest", reflect.TypeOf((*MockPortoAPI)(nil).WriteRequest), arg0)
}
