# syntax=docker/dockerfile:1
FROM ubuntu:22.04

RUN apt update

RUN apt install -y \
    g++ \
    cmake \
    protobuf-compiler \
    libprotobuf-dev \
    libgoogle-perftools-dev \
    libnl-3-dev \
    libnl-genl-3-dev \
    libnl-route-3-dev \
    libnl-idiag-3-dev \
    libncurses5-dev \
    libelf-dev \
    zlib1g-dev \
    pandoc \
    libseccomp-dev \
    libtool-bin \
    libbpf-dev


