// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: seccomp.proto

package seccomp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EAction int32

const (
	EAction_Allow       EAction = 0
	EAction_Errno       EAction = 1
	EAction_Trace       EAction = 2
	EAction_Notify      EAction = 3
	EAction_Log         EAction = 4
	EAction_Trap        EAction = 5
	EAction_KillProcess EAction = 6
	EAction_Kill        EAction = 7
)

// Enum value maps for EAction.
var (
	EAction_name = map[int32]string{
		0: "Allow",
		1: "Errno",
		2: "Trace",
		3: "Notify",
		4: "Log",
		5: "Trap",
		6: "KillProcess",
		7: "Kill",
	}
	EAction_value = map[string]int32{
		"Allow":       0,
		"Errno":       1,
		"Trace":       2,
		"Notify":      3,
		"Log":         4,
		"Trap":        5,
		"KillProcess": 6,
		"Kill":        7,
	}
)

func (x EAction) Enum() *EAction {
	p := new(EAction)
	*p = x
	return p
}

func (x EAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EAction) Descriptor() protoreflect.EnumDescriptor {
	return file_seccomp_proto_enumTypes[0].Descriptor()
}

func (EAction) Type() protoreflect.EnumType {
	return &file_seccomp_proto_enumTypes[0]
}

func (x EAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EAction) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EAction(num)
	return nil
}

// Deprecated: Use EAction.Descriptor instead.
func (EAction) EnumDescriptor() ([]byte, []int) {
	return file_seccomp_proto_rawDescGZIP(), []int{0}
}

type ECompare int32

const (
	ECompare_Ne       ECompare = 0
	ECompare_Lt       ECompare = 1
	ECompare_Le       ECompare = 2
	ECompare_Eq       ECompare = 3
	ECompare_Ge       ECompare = 4
	ECompare_Gt       ECompare = 5
	ECompare_MaskedEq ECompare = 6
)

// Enum value maps for ECompare.
var (
	ECompare_name = map[int32]string{
		0: "Ne",
		1: "Lt",
		2: "Le",
		3: "Eq",
		4: "Ge",
		5: "Gt",
		6: "MaskedEq",
	}
	ECompare_value = map[string]int32{
		"Ne":       0,
		"Lt":       1,
		"Le":       2,
		"Eq":       3,
		"Ge":       4,
		"Gt":       5,
		"MaskedEq": 6,
	}
)

func (x ECompare) Enum() *ECompare {
	p := new(ECompare)
	*p = x
	return p
}

func (x ECompare) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ECompare) Descriptor() protoreflect.EnumDescriptor {
	return file_seccomp_proto_enumTypes[1].Descriptor()
}

func (ECompare) Type() protoreflect.EnumType {
	return &file_seccomp_proto_enumTypes[1]
}

func (x ECompare) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ECompare) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ECompare(num)
	return nil
}

// Deprecated: Use ECompare.Descriptor instead.
func (ECompare) EnumDescriptor() ([]byte, []int) {
	return file_seccomp_proto_rawDescGZIP(), []int{1}
}

type TArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index   *uint64   `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	Compare *ECompare `protobuf:"varint,2,req,name=compare,enum=seccomp.ECompare" json:"compare,omitempty"`
	Value   *uint64   `protobuf:"varint,3,req,name=value" json:"value,omitempty"`
}

func (x *TArg) Reset() {
	*x = TArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seccomp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TArg) ProtoMessage() {}

func (x *TArg) ProtoReflect() protoreflect.Message {
	mi := &file_seccomp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TArg.ProtoReflect.Descriptor instead.
func (*TArg) Descriptor() ([]byte, []int) {
	return file_seccomp_proto_rawDescGZIP(), []int{0}
}

func (x *TArg) GetIndex() uint64 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *TArg) GetCompare() ECompare {
	if x != nil && x.Compare != nil {
		return *x.Compare
	}
	return ECompare_Ne
}

func (x *TArg) GetValue() uint64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type TAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action *EAction `protobuf:"varint,1,req,name=action,enum=seccomp.EAction" json:"action,omitempty"`
	Value  *uint64  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (x *TAction) Reset() {
	*x = TAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seccomp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TAction) ProtoMessage() {}

func (x *TAction) ProtoReflect() protoreflect.Message {
	mi := &file_seccomp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TAction.ProtoReflect.Descriptor instead.
func (*TAction) Descriptor() ([]byte, []int) {
	return file_seccomp_proto_rawDescGZIP(), []int{1}
}

func (x *TAction) GetAction() EAction {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return EAction_Allow
}

func (x *TAction) GetValue() uint64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type TRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Syscall *string  `protobuf:"bytes,1,req,name=syscall" json:"syscall,omitempty"`
	Args    []*TArg  `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
	Action  *TAction `protobuf:"bytes,3,req,name=action" json:"action,omitempty"`
}

func (x *TRule) Reset() {
	*x = TRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seccomp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TRule) ProtoMessage() {}

func (x *TRule) ProtoReflect() protoreflect.Message {
	mi := &file_seccomp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TRule.ProtoReflect.Descriptor instead.
func (*TRule) Descriptor() ([]byte, []int) {
	return file_seccomp_proto_rawDescGZIP(), []int{2}
}

func (x *TRule) GetSyscall() string {
	if x != nil && x.Syscall != nil {
		return *x.Syscall
	}
	return ""
}

func (x *TRule) GetArgs() []*TArg {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *TRule) GetAction() *TAction {
	if x != nil {
		return x.Action
	}
	return nil
}

type TProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DefaultAction *TAction `protobuf:"bytes,2,opt,name=default_action,json=defaultAction" json:"default_action,omitempty"`
	Rules         []*TRule `protobuf:"bytes,3,rep,name=rules" json:"rules,omitempty"`
}

func (x *TProfile) Reset() {
	*x = TProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seccomp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TProfile) ProtoMessage() {}

func (x *TProfile) ProtoReflect() protoreflect.Message {
	mi := &file_seccomp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TProfile.ProtoReflect.Descriptor instead.
func (*TProfile) Descriptor() ([]byte, []int) {
	return file_seccomp_proto_rawDescGZIP(), []int{3}
}

func (x *TProfile) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TProfile) GetDefaultAction() *TAction {
	if x != nil {
		return x.DefaultAction
	}
	return nil
}

func (x *TProfile) GetRules() []*TRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_seccomp_proto protoreflect.FileDescriptor

var file_seccomp_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x65, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x22, 0x5f, 0x0a, 0x04, 0x54, 0x41, 0x72, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2b, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x65, 0x63, 0x63, 0x6f, 0x6d,
	0x70, 0x2e, 0x45, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x02,
	0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x49, 0x0a, 0x07, 0x54, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x2e, 0x45,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x6e, 0x0a, 0x05, 0x54, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x12, 0x21, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x65, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x2e,
	0x54, 0x41, 0x72, 0x67, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x63,
	0x63, 0x6f, 0x6d, 0x70, 0x2e, 0x54, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7d, 0x0a, 0x08, 0x54, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73,
	0x65, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x2e, 0x54, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a,
	0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73,
	0x65, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x2e, 0x54, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75,
	0x6c, 0x65, 0x73, 0x2a, 0x64, 0x0a, 0x07, 0x45, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x09,
	0x0a, 0x05, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6e, 0x6f, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x63, 0x65, 0x10, 0x02, 0x12,
	0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x4c,
	0x6f, 0x67, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x72, 0x61, 0x70, 0x10, 0x05, 0x12, 0x0f,
	0x0a, 0x0b, 0x4b, 0x69, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x10, 0x06, 0x12,
	0x08, 0x0a, 0x04, 0x4b, 0x69, 0x6c, 0x6c, 0x10, 0x07, 0x2a, 0x48, 0x0a, 0x08, 0x45, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4e, 0x65, 0x10, 0x00, 0x12, 0x06, 0x0a,
	0x02, 0x4c, 0x74, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x65, 0x10, 0x02, 0x12, 0x06, 0x0a,
	0x02, 0x45, 0x71, 0x10, 0x03, 0x12, 0x06, 0x0a, 0x02, 0x47, 0x65, 0x10, 0x04, 0x12, 0x06, 0x0a,
	0x02, 0x47, 0x74, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x45,
	0x71, 0x10, 0x06, 0x42, 0x0a, 0x5a, 0x08, 0x73, 0x65, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x2f,
}

var (
	file_seccomp_proto_rawDescOnce sync.Once
	file_seccomp_proto_rawDescData = file_seccomp_proto_rawDesc
)

func file_seccomp_proto_rawDescGZIP() []byte {
	file_seccomp_proto_rawDescOnce.Do(func() {
		file_seccomp_proto_rawDescData = protoimpl.X.CompressGZIP(file_seccomp_proto_rawDescData)
	})
	return file_seccomp_proto_rawDescData
}

var file_seccomp_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_seccomp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_seccomp_proto_goTypes = []interface{}{
	(EAction)(0),     // 0: seccomp.EAction
	(ECompare)(0),    // 1: seccomp.ECompare
	(*TArg)(nil),     // 2: seccomp.TArg
	(*TAction)(nil),  // 3: seccomp.TAction
	(*TRule)(nil),    // 4: seccomp.TRule
	(*TProfile)(nil), // 5: seccomp.TProfile
}
var file_seccomp_proto_depIdxs = []int32{
	1, // 0: seccomp.TArg.compare:type_name -> seccomp.ECompare
	0, // 1: seccomp.TAction.action:type_name -> seccomp.EAction
	2, // 2: seccomp.TRule.args:type_name -> seccomp.TArg
	3, // 3: seccomp.TRule.action:type_name -> seccomp.TAction
	3, // 4: seccomp.TProfile.default_action:type_name -> seccomp.TAction
	4, // 5: seccomp.TProfile.rules:type_name -> seccomp.TRule
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_seccomp_proto_init() }
func file_seccomp_proto_init() {
	if File_seccomp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seccomp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seccomp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seccomp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seccomp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seccomp_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seccomp_proto_goTypes,
		DependencyIndexes: file_seccomp_proto_depIdxs,
		EnumInfos:         file_seccomp_proto_enumTypes,
		MessageInfos:      file_seccomp_proto_msgTypes,
	}.Build()
	File_seccomp_proto = out.File
	file_seccomp_proto_rawDesc = nil
	file_seccomp_proto_goTypes = nil
	file_seccomp_proto_depIdxs = nil
}
